release-engineering/pushsource

.github/CODEOWNERS
This repo is still undergoing initial development and code review
is not yet enforcing. Don't set CODEOWNERS for the time being,
otherwise it will spam owners for every incoming PR.
=> Don't set CODEOWNERS yet

tox.ini
We need to install rpm-py-installer for docs target too.
=> Fix build of docs in CI

src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/helpers.py, src/pushsource/helpers.py, tests/koji/test_koji.py
If the source is given an integer-like string by URL, it must be
converted into a real integer before use in an XML-RPC call to
koji.
=> koji: fix handling of build & rpm IDs

docs/userguide.rst, src/pushsource/_impl/backend/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/helpers.py, tests/helpers/test_argument_helpers.py
The helpers module is intended to include functions which assist
in implementing new sources, mainly to do with parsing arguments
from URLs.
I don't feel confident in this API, as the contents are fairly
arbitrary according to the sources which have been implemented so
far.  Let's make it private for now so we don't have to commit
to maintaining compatibility.
=> Make pushsource.helpers private

docs/conf.py, docs/index.rst, docs/schema/staged.rst, src/pushsource/_impl/backend/staged/staged_files.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/_impl/backend/staged/staged_utils.py, src/pushsource/_impl/model/file.py, src/pushsource/_impl/schema/__init__.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/staged/data/dupe_meta/staged.yaml, tests/staged/data/incomplete_channel_dumps/staged.yaml, tests/staged/data/simple_channel_dumps/staged.yaml, tests/staged/data/simple_files/staged.yaml, tests/staged/test_staged_basic.py, tests/staged/test_staged_simple_files.py
staged.yaml / pub-mapfile.json is now validated against a documented
schema. Implementing this schema also uncovered missing support for
a 'version' attribute, which was fixed.
=> Define and enforce a schema for staging metadata

src/pushsource/_impl/backend/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py
The meaning is always the same as on the base class, and these
doc strings don't make it into the generated HTML docs anyway.
=> Drop doc strings for __iter__ methods

docs/sources/errata.rst, docs/userguide.rst
Code for ErrataSource uses 'errata' for advisory IDs, but many
examples in docs incorrectly used 'advisory' instead.
=> docs: fix argument name for errata source

docs/sources/base.rst, src/pushsource/__init__.py, src/pushsource/_impl/__init__.py, src/pushsource/_impl/source.py, tests/source/test_source.py
Previously, if a bad source URL was given, typically a confusing
KeyError would be raised. Let's use a specific type of error to
make it more clear that an incorrect URL is the source of the
problem.
=> Improve errors when bad source URLs are used

docs/sources/errata.rst
koji_source needs a full valid source URL, not just a koji URL
(as a different kind of source could potentially be used).
It should be "koji:\<koji-hub-url\>" and not just "\<koji-hub-url\>".
=> docs: fix incorrect usage of koji_source in example

CHANGELOG.md, src/pushsource/_impl/backend/koji_source.py, tests/koji/test_koji.py
When we can't find a requested RPM on the filesystem, previously
we'd log that RPMs were not found but it wasn't clear what it
means. Adjust the error message to include the paths of the missing
RPM(s) to make it more obvious.
=> koji: improve log messages on missing RPM(s)

CHANGELOG.md, src/pushsource/_impl/source.py, tests/source/test_source_register.py
For any registered backend, the Source class needs to know if
the backend accepts a 'url' argument, which is done by inspecting
the backend's signature.
However, on Python 2, this only works on "pure" python functions,
and not the output of functools.partial. This meant that if you
obtained a callable by get_partial and then gave it to
register_backend (which is the intended use), you'd get a crash
along the lines of:
TypeError: arg is not a Python function
Let's avoid functools.partial and instead manually bind the function
we're returning, to improve Python 2 compatibility.
=> Fix crash on python2 if using get_partial with register_backend

CHANGELOG.md, src/pushsource/_impl/model/erratum.py, src/pushsource/_impl/schema/errata-schema.yaml, tests/staged/data/simple_errata/dest1/ERRATA/advisory2.json, tests/staged/test_staged_simple_errata.py
The schema/model for these fields was too strict - in reality,
the id and title fields on references are null for some errata.
=> Fix crash on null id/title in erratum references

CHANGELOG.md, setup.py, src/pushsource/_impl/model/base.py, tests/model/test_push_item_read_sums.py
As explained in doc string. Calculating checksums is potentially
expensive, and so it is not filled in implicitly by all pushsource
backends. The caller is able to control when sums are calculated
This utility method makes it simple to obtain checksums only when
needed, e.g. a Pub-style multithreaded "computing checksums" step
could be easily implemented via a threadpool executor by:
items = executor.map(lambda i: i.with_checksums(), items)
=> Introduce PushItem.with_checksums for calculating sums

src/pushsource/_impl/backend/staged/staged_source.py
It probably makes sense for a user to see this every time rather
than just when debugging, so let's make it INFO.
=> staged: bump verbosity for one log

test-requirements.in
Previously, test-requirements.in was not added to the repo.
This causes a problem: dependabot will not add entries to the
test-requirements.txt file for any new indirect dependencies
as they are introduced by upgrades to other packages. Since we
use hash checking mode, this causes CI to fail completely as the
resulting test-requirements.txt is not installable unless hashes
are present for *all* dependencies, both direct and indirect.
Adding test-requirements.in fixes this, because it causes
dependabot to run pip-compile in order to regenerate the
corresponding .txt, and pip-compile does support updating indirect
dependencies where needed, including hashes.
See also the (internal) mail https://url.corp.redhat.com/e051f38
for more context on the problem and solution.
=> Add test-requirements.in to improve effectiveness of dependabot

CHANGELOG.md, src/pushsource/_impl/model/erratum.py, src/pushsource/_impl/schema/errata-schema.yaml, tests/errata/data/RHBA-2020:0518.yaml, tests/errata/data/RHSA-2020:0509.yaml
This field was declared as a string (or null) and is always stored
as such.
In practice, because Bugzilla uses integers for bug IDs, some older
data exists which had used integers rather than strings. Let's
tolerate such data as well - it's converted to string on load.
=> erratum: allow integers for 'id' within references

CHANGELOG.md, src/pushsource/_impl/model/erratum.py, src/pushsource/_impl/schema/errata-schema.yaml, tests/errata/data/RHSA-2020:0509.yaml, tests/errata/test_errata_rpms.py
The schema for the "pkglist" field within errata had set "name"
as a required field.
I have discovered some data in the wild for which that field is
missing, and after reviewing the code of pulp_rpm it seems that
data without this field is in fact able to be uploaded, so the
schema was too strict. Adjust so that 'name' (and 'short') are
both considered optional, with blank defaults.
=> staged: fix overly strict erratum pkglist schema

CHANGELOG.md, src/pushsource/_impl/schema/staged-schema.yaml, tests/staged/data/unsupported/staged.yaml
The intended behavior for old unsupported content types such as
DOCKER is to log a warning and ignore discovered push items.
However, it is likely that the metadata file for the push also
has entries for those files. In that case, these must be able to
pass validation, otherwise we'll get an error rather than a
warning.
To make that work, add a loose schema for those unsupported types.
It does not validate any attributes on the metadata, as the goal
is simply to ignore these entries.
=> staged: accept metadata for legacy unsupported content

CHANGELOG.md, src/pushsource/_impl/schema/staged-schema.yaml, tests/staged/data/simple_files/staged.yaml, tests/staged/test_staged_simple_files.py
This field in schema had been declared to have a minimum length of
at least one character (i.e. not an empty string), since it seems
that the description may as well be omitted if you're going to pass
an empty string.
However, in practice it seems that empty strings have genuinely
been used in the past here and files with empty descriptions (rather
than absent) do exist in the wild. It was not intended for the
schema to block any existing workflows, so let's loosen it up and
make it accept this data.
=> Fix too strict handling of 'description'

CHANGELOG.md, src/pushsource/_impl/model/erratum.py, src/pushsource/_impl/schema/errata-schema.yaml, tests/errata/data/RHSA-2020:0509.yaml, tests/errata/test_errata_rpms.py, tests/staged/data/simple_errata/dest1/ERRATA/advisory2.json, tests/staged/test_staged_simple_errata.py
The reboot_suggested field is unusual in that it can appear
at two levels within an erratum: once at the top level, but also
within each entry under 'pkglist'.
The latter previously was incorrectly missing from the schemas and
model in this library, leading to a crash if an attempt was made
to push an erratum using the field in pkglist. This is important
because it's actually the field in pkglist which is consumed by
yum (and the usage of the other field is unclear - it's possible
it only exists for historical reasons).
Let's update the model and schema to accept reboot_suggested in
pkglist, update a few tests to ensure that this is covered, and
also add a warning about the quirkiness of this field to the docs.
=> Fix missing reboot_suggested field from erratum pkglists

test-requirements.txt
Since dependabot is broken, it seems that test requirements
got broken as well.
There was a clash with version lazy-object-proxy package that were required from different packages. Trying to fix this
manually.
=> Fix test requirements

CHANGELOG.md, src/pushsource/__init__.py, src/pushsource/_impl/backend/staged/staged_ami.py, src/pushsource/_impl/model/__init__.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/staged/data/simple_ami/staged.yaml, tests/staged/data/simple_ami_with_bc/staged.yaml, tests/staged/test_staged_simple_ami.py
This commit adds billing codes field for AMI staged push item schema
and model.
This field is optional and it's a dict consisting of
- "name", that is arbitrary string used for compiling unique AMI image name 
- "codes" list of actual billing codes that should be for AMI registering.
=> Add billing codes to staged AMI push item

CHANGELOG.md, src/pushsource/_impl/source.py, tests/source/test_source.py
Previously if you've prepared a source like this:
```python
src = Source.get_partial('somebackend', ...)
inst1 = src(key1='value1')
inst2 = src(key2='value2')
```
...then the second call would be passed both key1 and key2
incorrectly.
This happened due to some code which intended to merge two
dicts together, but it did this via an in-place update of
a dict used at every call rather than making a copy.
Fix it to do the merge safely.
I don't think this affects any current usage of the library,
but it would interfere with errata source being prepared in
RHELDST-5430.
=> Fix argument leaks in get_partial

docs/conf.py, docs/sources/errata.rst, docs/sources/koji.rst, docs/sources/staged.rst
autoclass_content="both" means that we always render docstrings
of \_\_init\_\_. Unfortunately, for attrs-generated classes such as
all the PushItem implementations, the \_\_init\_\_ doc string is always
"Method generated by attrs for class \<foo\>" which seems ugly and
confusing.
Let's suppress that, and just use the class-level doc string instead
by default. Classes where \_\_init\_\_ needs documenting can explicitly
enable it.
=> docs: clean up docs for constructors

docs/sources/base.rst
Special methods (\_\_foo\_\_) are not included in docs by default,
even if they have doc strings.
It makes sense to include this one, since the whole point of a
Source instance is to be iterated over. The purpose of the class
may be rather unclear if this can't be seen.
=> docs: fix missing doc for Source.__iter__

docs/conf.py, docs/ext/attr_types.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/model/base.py, src/pushsource/_impl/model/erratum.py
It is irritating that we've been defining type metadata for
attributes using attrs library, yet this info hasn't made it into
docs.
As I understand it, once we can drop python2 support, we could use
python3 native type hints and type info would make it into docs
automatically. Until then, turns out it's fairly simple to extend
sphinx to pull out that metadata ourselves, so let's do that.
This means an attribute declared as attr.ib(type=foo, ...) will
appear with "Type: foo" in the generated docs.
It works automatically for almost everything, but a few doc strings
were also tweaked to work better:
- in some cases, a type name previously embedded in doc strings was
removed because it would now be redundant.
- in other cases, mainly list types, the type is written out
explicitly because …
=> docs: improve type info for attrs-generated classes

CHANGELOG.md, src/pushsource/_impl/backend/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/_impl/source.py, tests/source/test_source_reset.py
When a user of this library needs to customize backends, as is the
case in Pub, writing tests for that code can be cumbersome as the
tests would have to carefully undo any customizations made to ensure
that custom backends aren't left behind interfering with later tests.
Let's add a reset method so we can simply do "Source.reset()" during
test cleanup, to put everything back to the original state.
Refactoring connected with RHELDST-5431.
=> Add a reset() feature to remove all custom backends

tests/errata/conftest.py, tests/errata/test_errata_errors.py, tests/errata/test_errata_metadata.py, tests/errata/test_errata_modules.py, tests/errata/test_errata_rpms.py
fake_koji and fake_errata_tool were set up identically across
several tests. Adding them to conftest.py allows removing this
duplicate code.
=> refactor: deduplicate fixtures in errata tests

CHANGELOG.md, src/pushsource/_impl/backend/errata_source.py, tests/errata/test_errata_metadata.py
Due to incorrect usage of os.path.join, if errata source was used
with a URL having a path component such as
https://errata.example.com/path, the hostname portion would be lost
and we'd try to construct an XML-RPC client with
"/path/errata/errata_service" as the URL.
Fix that by using os.path.join only on the needed components (we
don't need it when joining the parsed URL netloc and path back
together).
=> errata: fix handling of XML-RPC URL where a path component is included

CHANGELOG.md, src/pushsource/_impl/model/conv.py, src/pushsource/_impl/model/erratum.py, tests/model/test_errata_type.py
This field was documented as having values either "bugfix", "security"
or "enhancement", but there were a couple of issues with it:
- this was not enforced, so actually any values could appear there
- some ancient errata found in the wild use other values here, like
"RHBA" and "RHSA"
Fix both of these by requiring that valid values are used, and
automatically converting known legacy values when data is loaded.
=> errata: convert and validate 'type' field

CHANGELOG.md, docs/sources/koji.rst, src/pushsource/_impl/backend/errata_source.py, src/pushsource/_impl/backend/koji_source.py, tests/koji/conftest.py, tests/koji/test_koji.py, tests/koji/test_koji_module.py
ET requests modules by filename, e.g. modulemd.x86_64.txt.
Previously, we had errata source query koji source and then filter
the returned values according to ET's desired filenames. Let's
instead make koji source natively support filtering by way of a new
parameter.
Motivation: koji source will soon need to start parsing these
modulemd files so that the NSVCA can be put onto push items.
If we do this for files which will be then filtered by the errata
source, we're negatively impacting the performance and reliability
by loading data we don't need. It's better if we can tell koji
source in advance exactly which files we're interested in.
=> refactor: move modulemd filtering from errata source to koji source

CHANGELOG.md, src/pushsource/_impl/backend/errata_source.py, tests/errata/test_errata_missing_modules.py
If ET metadata requests the usage of some modulemd but we can't find
that in koji, we should give a fatal error rather than silently ignoring
it.
=> errata: detect & complain on missing modules

CHANGELOG.md, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/modulemd.py, tests/koji/data/modulemd-multiple.yaml, tests/koji/data/modulemd-varnish-x86_64.yaml, tests/koji/test_koji_module.py
Testing this code with Pub revealed a behavior difference: in Pub
code, we load modulemd files and use their NSVCA as the push item
name. In this library we were not doing that, and instead using
the modulemd filename as push item name.
Although it's a bit annoying that we have to parse the modulemd
files before we can return push items, overall the Pub behavior
seems better as the NSVCA is a much better identifier for what's
being pushed than a generic filename like modulemd.<arch>.txt.
So let's do the same here.
As a compromise, we still use the filename as a fallback when the
file isn't available. This is done since loading the file needs
koji's NFS volume available, which is true in production but won't
be the case in many development and testing scenarios.
=> koji: use NSVCA as module push item name

CHANGELOG.md, src/pushsource/_impl/backend/errata_source/__init__.py, src/pushsource/_impl/backend/errata_source/errata_client.py, src/pushsource/_impl/backend/errata_source/errata_source.py, tests/errata/conftest.py, tests/errata/data/RHEA-2020:0346.yaml, tests/errata/fake_errata_tool.py, tests/errata/test_errata_modules.py
Integrate support for get_ftp_paths API into errata backend.
This can now result in the 'dest' for one RPM push item having
a mixture of rhsm-pulp repo IDs and FTP paths. This will allow
alt-src pushes to work on top of errata backend.
Other tweaks include:
- drop the 'target' argument to errata backend (which was not used).
It seems we ought not to need this.
For now the design now is that the source will give you back all
kinds of destinations (and if you only want to deal with certain
types, e.g. you don't want the ftp paths, you need to filter them
yourself). It's possible some optional filtering arguments will be
added here later.
- separate the low-level code which calls ET methods into a new
errata_client module
Note: the backend remains marked as a technical preview with
no …
=> errata: support FTP paths for RPMs

CHANGELOG.md, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/model/rpm.py, tests/errata/test_errata_modules.py, tests/koji/fake_koji.py
When we're dealing with modular RPMs loaded via ET, there are two
relevant builds in koji:
- build containing RPMs
- build containing modulemds
We had not previously made the latter available anywhere. Add it
to a new attribute because some alt-src use-cases need it.
=> errata: add module_build onto RPM push items

CHANGELOG.md, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/helpers.py, src/pushsource/_impl/model/conv.py, tests/errata/test_errata_rpms_filter.py
Add a parameter which allows adjusting the set of arches included in
returned RPMs.
The primary use-case for this at the moment is during alt-src pushes.
In that case, we know that only source RPMs are of interest, and
querying for other RPM arches only costs extra time.
=> errata: support filtering RPMs by arch

CHANGELOG.md, src/pushsource/__init__.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/model/__init__.py, src/pushsource/_impl/model/modulemd.py, tests/koji/test_koji_module.py
We had previously used ModuleMdPushItem to represent any
modulemd-related archives on a koji build. This included both built
modules such as modulemd.x86_64.txt and module source files such as
modulemd.src.txt.
We shouldn't really do that though, because they're very different
things. The document format is not the same, and the expected usage of
each type of push item is completely different (e.g. modulemd.src.txt
are not meant to be uploaded to yum repos).
Let's model them as separate types so the caller can process the two
types differently and won't accidentally try to handle a source modulemd
in the same way as a built modulemd.
=> Introduce separate class for modulemd sources

docs/conf.py, docs/ext/attr_index.py
Previously, in the docs for push item classes, inherited attributes
were not displayed. This is annoying since it means one needs to look at
the base class and subclass docs together to understand what's
available. In extreme cases such as ProductIdPushItem which don't have
any of their own attributes, it gives the impression of a completely
empty class.
Unfortunately none of the built-in sphinx autodoc features seem able to
solve this.  There is an :inherited-members: option, but if enabled it
copies the entire doc strings from the base classes without any
indication of what's inherited and what's not, which is far too
verbose.
So let's add a little extension ourselves which generates a list under
the class description.
=> docs: add an attribute index onto push items

CHANGELOG.md, src/pushsource/_impl/backend/errata_source/errata_source.py, tests/errata/data/RHEA-2020:0346-no-module-ftp-paths.yaml, tests/errata/test_errata_module_sources.py, tests/koji/fake_koji.py
The get_ftp_paths method on ET has a 'modules' key which is meant to be
used for push of modulemd sources. Let's start making appropriate use
of that within the errata source.
=> errata: provide modulemd sources, respecting ftp_paths

docs/model/modulemd.rst, tests/docs/test_autodoc_coverage.py
Adding this to docs was forgotten when the new class was introduced.
Add it now, along with a test which prevents the same mistake in the
future.
=> docs: fix missing ModuleMdSourcePushItem

docs/model/containers.rst, src/pushsource/__init__.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/model/__init__.py, src/pushsource/_impl/model/container.py, tests/baseline/cases/koji-source-container.yml, tests/koji/data/builds/openstack-swift-container-container-source-16.1.6-6.1.yaml, tests/koji/data/dump
Source container images are significantly different in nature from a
regular container image and they don't get pushed in the same way.
Introduce a subtype for them.
=> Introduce SourceContainerImagePushItem

requirements.txt, src/pushsource/_impl/backend/koji_containers.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/compat.py, src/pushsource/_impl/model/container.py, tests/baseline/cases/errata-containers-legacy-repos.yml, tests/baseline/cases/errata-containers.yml, tests/baseline/cases/koji-source-container.yml
Adds a few fields known to be used by consumers:
- architecture of image
- source_tags (tags used by build system). Sometimes used to set
default tags during push.
- labels, at least com.redhat.*, used for determining whether an
image includes operator metadata.
=> Add miscellaneous container image fields

src/pushsource/_impl/backend/koji_source.py
A minor tweak to tolerate cases of a container build which has an
'image' field present but an empty dict. Rather than refusing to
handle it, let's continue and generate near-empty push items.
This is probably irrelevant to any real builds produced in recent
years. The motivation is improved compatibility with Pub, which
does accept builds like this and has some tests based on it
(though it's unclear if any such builds actually exist beyond
Pub's testdata)
=> koji: tolerate container builds with empty 'image'

CHANGELOG.md, docs/sources/errata.rst, docs/sources/koji.rst, docs/userguide.rst, src/pushsource/_impl/model/base.py
Errata source and all the new container-related push items are ready to
be taken into general use and have been tested with Pub already. Do a
pass over the docs to reflect this:
- update errata and koji source docs to mention container image support
- remove the note presenting errata source as a 'tech preview' since
it's about to be put into production
- fix one inaccurate note about PushItem.name for container images
=> docs: update for completion of errata source

src/pushsource/_impl/backend/koji_source.py
In some error cases, a pattern was being used here like this:
- make an error message
- log the message as an ERROR
- raise exception with same message
The idea behind it is that, when raising the exception, we don't know
if anyone's going to catch it and log appropriately. If they don't,
then we may have created a situation we can't debug, and we'll surely
wish we had added that log message.
However, if the exception *is* caught and logged then this ends up with
duplicate messages.
Based on testing with Pub, the "duplicate message" case is more common,
so let's stop doing that and just raise the exception without logging an
error. We can still log as DEBUG, which will not show the message by
default but still gives us a way to enable the messages if needed.
=> koji: avoid some duplicate logs

src/pushsource/_impl/backend/errata_source/errata_client.py, tests/errata/test_errata_client_logging.py
The ET client was too quiet previously. Add the following logs:
- INFO after each advisory is successfully queried
- DEBUG around every API call, successful or otherwise
- disabled by default
- uses structured logging so it can integrate with Pub's JSONL logs,
which would enable us to gather metrics on performance
=> errata: add some logging around API calls

examples/list-push-items
list-push-items can be used to dump whatever push items are available
in a given source.
Previously, the output format was something ad-hoc put together.
Let's adjust the format and add some more useful options:
-  python: repr() of items (can be pasted straight back into python code and it'll work to create the items)
- python-black: like python but also formatted nicely
- yaml: dump all items as a YAML list
With these new formats you can copy-paste the output of this
script into some docs or a test and have it make sense.
=> examples: add better formatting to list-push-items

CHANGELOG.md, README.md, docs/index.rst, docs/userguide.rst, examples/dump-pub-staged, examples/list-push-items, src/pushsource/_impl/backend/errata_source/errata_client.py, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/_impl/source.py, tests/baseline/test_baseline.py, tests/errata/test_errata_metadata.py, tests/errata/test_errata_modules.py, tests/koji/test_koji.py, tests/source/test_source_context.py, tests/source/test_source_reset.py
Previously, sources were used like this:
source = Source.get(...)
for item in source:
...
Problem: a lot of the sources spawn additional threads internally and
there was no way to clean them up other than relying on GC (which
is problematic if there can be cycles between threads).
This was a bit of a design flub which was missed since the typical
use-case for a source is to only create one of them in the lifecycle
of your task/script/etc. However, it becomes relevant in cases such
as test suites, where hundreds of tests might each create Source
instances - leading to hundreds of threads spawned and never cleaned
up until all tests finish.
To fix this we now provide support for with-statements, which really
should have been there since the beginning. Now the recommended way
to use a source …
=> Add enter/exit support to fix lifecycle/resource leak issue

.pylintrc
pylint 2.9.0 (2021-06-29) introduced unused-private-member checker,
but it wrongly flags some of our code as unused (code using
@handles_type decorator in staged backend).
=> pylint: disable unused-private-member

CHANGELOG.md, requirements.txt, src/pushsource/_impl/backend/errata_source/errata_client.py, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py
Naming these is a good idea because:
- the name will be reused in any created threads, so we can
figure out which code created which thread
- the name will appear in prometheus metrics
=> refactor: give all executors a meaningful name

CHANGELOG.md, src/pushsource/_impl/backend/broken_rpmlib.py, src/pushsource/_impl/backend/staged/staged_rpm.py, tests/staged/test_broken_rpmlib.py
Some of the code in the staged backend depends on kobo.rpmlib, which in
turn depends on python bindings to rpm.
Previously, it was a hard dependency that these bindings must be
available even for "import pushsource" to succeed. Let's make it a bit
friendlier and avoid a hard dependency at import-time: we will only
raise if we reach the relevant piece of code at runtime.
Motivations for doing this now include:
- Python bindings to rpm aren't easy to install in all contexts.
Although there's an "rpm-py-installer" package on pypi which can help,
the way it works is unusual and insecure, and I don't think it's
appropriate to declare a dependency on that package within
install_requires.
- Recently, pubtools-1.1.0 was released, which now attempts to eagerly
import all installed pubtools-* …
=> Tolerate absence of rpm at import time

.gitignore, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/helpers.py, tests/errata/test_errata_metadata.py, tests/helpers/test_argument_helpers.py
Update `ErrataSource` to use https rather than http for Errata Tool XML-RPC endpoint requests. 
Historically, the `ErrataSource` constructor allowed calling code to pass URLs with either http or https schemes, and would force http behind the scenes. For compatibility, the `ErrataSource` constructor still allows calling code to use http or https, but now forces https behind the scenes.
=> Use https for errata

CHANGELOG.md, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/_impl/helpers.py, tests/helpers/test_futures_timeout.py
Mitigate spurious TimeoutError for slow caller [RHELDST-6064]
Previously iterating over any *Source object suffered from
spurious TimeoutError when caller was slow. The generator 'as_completed'
is unable to reset or stop timer for timeout, the timer for timeout
starts in original call to this generator.
Instead an alternative generator called 'as_completed_with_timeout_reset'
was implemented in helpers.py. It provides following functionality:
- yields finished futures as soon as any of them is finished
- after a finished future is yielded, there is no timeout check in
place after yield
- timeout is only applied when next item from generator is requested
This approach allows caller to work as long as it needs, TimeoutError
is raised only in case when next requested item from pushsource …
=> Mitigate spurious TimeoutError for slow caller [RHELDST-6064]

src/pushsource/_impl/backend/registry_source.py, tests/test_registry.py
The point of the list_argument helper is that it will accept both
a true list (preferred in the case of programmatically creating a
Source) and a comma-separated string (preferred in the case of
obtaining source by URL). Calling split() on the input defeats the
purpose.
Fix it to use list_argument appropriately and ensure that each of
the 'list' and 'comma-separated' cases are covered by at least one
test.
=> registry: fix list handling for some arguments

docs/index.rst, docs/sources/registry.rst, src/pushsource/_impl/backend/registry_source.py
- add registry to docs/index.rst so it appears under navigation
- fix various incorrect examples, argument names, etc.
- add some details (e.g. authentication) and remove others
- tweak style for consistency
=> docs: fix & tweak docs for new registry source

.github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/tox-test.yml
Use python 3.9 as the new minimum version for py3.
The motivation for changing it now is to resolve the issue seen in
pip-compile PR #191. The problem is that pip-compile is already using
python 3.9 but other CI configs used 3.8. This is not valid, as the set
of resolved dependencies can differ between the two versions.
It could be solved by either downgrading the python used for pip-compile
or upgrading the python used elsewhere. In this commit I pick the latter
approach, seeing as python 3.9 is readily available on all the py3
target platforms.
=> ci: bump py3 version to 3.9

src/pushsource/_impl/utils/containers/request.py, test-requirements.in, test-requirements.txt
Also added importlib-resources explicitly to test-requirements.in to
avoid error of unpinned version when installing dependencies (
In --require-hashes mode, all requirements must have their
versionspinned with == )
=> get_basic_auth should return tuple

src/pushsource/_impl/backend/registry_source.py, src/pushsource/_impl/utils/containers/__init__.py, src/pushsource/_impl/utils/containers/request.py, tests/test_containers.py, tests/test_registry.py
In order to allow to push to pulp target, push item has to contain
digests for all manifest types
=> Fetch digests for all manifest types for registry source

src/pushsource/_impl/source.py, tests/source/test_source_partial_with_url.py
If a source is defined like this:
class MySource:
def __init__(self, url, arg1=..., arg2=...):
...
...and registered as 'my-source', then as a convenience one may
refer to the source as 'my-source:/some/url' rather than
'my-source:url=/some/url'.
Problem: if get_partial was used to wrap the source, this special
handling for the url argument would be unexpectedly lost.
Fix it by ensuring that get_partial propagates whether or not a
source accepts a 'url' argument. Since functools.wraps does this
natively on python 3.4+, it will be possible to drop this when py2
support goes away.
=> Fix get_partial breaking special handling of 'url'

tests/registry/test_calculate_digest.py, tox.ini
The recently added registry source never tested digest calculation for a
schema1 manifest, dropping the coverage slightly from 100%. Get it back.
CI is meant to reject changes which drop coverage, but codecov/patch has
been a little flaky recently. Just use the built-in pytest-cov option to
lock the coverage to 100% so we aren't relying on a remote service for
that.
=> tests: fix missing coverage, lock to 100%

src/pushsource/_impl/backend/errata_source/errata_source.py, tests/errata/data/RHEA-2020:0346-no-cdn-list.yaml, tests/errata/test_errata_module_sources.py
If we're processing modules in ftp_paths and we fail to find an existing
ModulemdSourcePushItem for a given entry, we would previously give an
error message indicating that modulemd sources are missing from koji.
Actually, that is only one of two reasons we might fall into this error
case. The other reason is that the same modules might have been missing
from the cdn_file_list response.
Update the code to differentiate between the two cases. In the ET case,
we will not currently treat that as a fatal error since the behavior of
these methods is not strictly defined. However, it's sufficiently
unexpected to generate a warning.
=> errata: improve error handling on modulemd source lookup

docs/userguide.rst
Pull spec is provided as an 'image' argument, so this example was
slightly wrong.
=> docs: fix a user guide mistake for registry source

src/pushsource/_impl/backend/registry_source.py, src/pushsource/_impl/utils/containers/request.py, tests/test_containers.py, tests/test_registry.py
Unify inspected output for v1 images. Also tolarted 404 when getting
digest of manifest for containers which have only one type of the
manifests
=> Fixed inspecting v1 images

CHANGELOG.md, setup.py, src/pushsource/_impl/backend/staged/staged_files.py, src/pushsource/_impl/backend/staged/staged_utils.py, src/pushsource/_impl/model/conv.py, src/pushsource/_impl/model/file.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-files.yml, tests/model/test_file_push_item.py, tests/staged/data/simple_files/staged.yaml
This attribute provides a way to manipulate the order in which files are
displayed when presented in a UI.
The field can be populated in staging metadata, at the same level of the
existing 'version' field. This format is the same as Pub apparently
supported prior to migrating to the pushsource library.
The absence of this field from pushsource up to now could be considered
an oversight. Users have managed to get by without it due to some
lower-level tools able to manipulate the relevant Pulp fields directly,
but it would be preferable to fold this into the regular push workflow.
=> Introduce FilePushItem.display_order

.pre-commit-config.yaml, test-requirements.in, tests/test_containers.py, tox.ini
black was previously integrated into both tox and pre-commit.
The version used by tox would be managed by pip-compile.
This causes some issues: if our pip-compile github action updates
to a new version of black which adjusts any formatting, this will cause
CI to fail as it does not automatically run black over all files and
include changes in the commit.
pre-commit.ci on the other hand does support doing exactly that.
Therefore, for black and similar "auto-fixing" tools, it seems better to
leave them solely to pre-commit and not try to include them in tox.
As part of this change, the pre-commit config for black was updated to
ensure pre-commit autoupdates will succeed from this point onwards.
=> Refresh integration with black, drop from 'tox -e static'

src/pushsource/_impl/compat_attr.py
Some of the commands based on this library are having memory usage
issues. According to my testing of a simple script which loads ~12000
push items, switching to slots-based classes will reduce the memory
usage of pushsource objects by 90%, and the overall memory usage of the
test script by ~33%. Let's do that to relieve the memory pressure.
=> Use slots-based classes for pushsource models

src/pushsource/_impl/model/conv.py
Astonishingly in python2 there is a crash bug in strptime which can
occur if the very first call to the function happens concurrently from
multiple threads. This is https://bugs.python.org/issue7980 which was
closed as "Won't Fix" since the problem is resolved in python3.
It can be worked around by calling the function once at import time,
when we're confident there won't be concurrent calls. Workaround is
inspired by [1].
[1] https://github.com/boto/boto/pull/1940/files
=> Work around python2 strptime thread-safety bug

docs/index.rst
New pages should be referenced from index.rst, otherwise there is no way
to navigate to them.
=> docs: fix DirectoryPushItem not reachable in docs

docs/userguide.rst, setup.py, src/pushsource/_impl/backend/errata_source/errata_source.py, src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/backend/registry_source.py, src/pushsource/_impl/backend/staged/staged_source.py, src/pushsource/_impl/source.py, tests/source/test_source_entrypoint.py
This library supports custom backends. A problem can arise: the
backend has to be registered by a call to Source.register_backend, and
if implementing a backend in a library, there may not be any place to
put that call where it's guaranteed to happen by the time it's needed.
Fix this by adding a 'pushsource' entry point group. A library can
define an entry point pointing at a module which calls register_backend.
If so, pushsource library will ensure the module is imported during the
first call to Source.get().
=> Allow locating pushsource backends via entry points

docs/userguide.rst, src/pushsource/_impl/backend/__init__.py, src/pushsource/_impl/backend/direct.py, tests/baseline/cases/direct-comps.yml, tests/baseline/cases/direct-dir.yml, tests/baseline/cases/direct-file.yml, tests/baseline/cases/direct-modulemd-src.yml, tests/baseline/cases/direct-modulemd.yml, tests/baseline/cases/direct-productid.yml, tests/baseline/cases/direct-rpm.yml
These new backends will simply construct and return a single push item
of any file-backed type, for example:
file:/my/file.txt
...will return a single FilePushItem having src="/my/file.txt" and some
other basic attributes.
These backends are not strictly required as they do not support anything
which is not already supported by the "staged" backend. There's also no
plan at the moment to make them usable from Pub.
The primary motivation here is to make development and testing of
downstream projects less cumbersome. For example, in pubtools-pulp if I
want to test pushing a certain RPM, I should be able to do simply:
pubtools-pulp-push --source rpm:test.rpm?dest=target-repo ...
... instead of having to create a staging directory, copy/symlink the
test RPM into it and remember to clean it up …
=> Introduce 'direct' backends

src/pushsource/_impl/utils/containers/request.py, tests/test_containers.py
The parameter "scope" will be added once it's not included in the response
from the registry
Refers to CLOUDDST-12357
=> Add missing "scope" parameter while requesting token

src/pushsource/_impl/utils/containers/request.py
Add the parameter "repo" while calling registry_request in get_blob,
otherwise "scope" may not be added while requesting token.
Refers to CLOUDDST-12357
=> Add missing parameter "repo"

src/pushsource/_impl/model/base.py, src/pushsource/_impl/model/cache.py, tests/model/test_field_caching.py
For push item sources such as staged and errata, fields like
'signing_key' and 'dest' will often have the same value across most or
even all of the loaded objects. This leads to tens of thousands of
copies of the same strings, wasting a bit of memory.
We can achieve some modest savings by caching/sharing values across
items. It is safe, since the shared values are immutable. This commit
implements such sharing for a handful of fields.
A few different caching approaches were tried here, but for most of
them the overhead of the cache exceeded the memory saved. In the end the
chosen strategy was to cache only the last couple of values per field,
which seems odd but works due to the typical usage patterns of push
items (constructing a lot of similar items at once). An included doc
string has …
=> Add caching for a few fields which often have duplicates [RHELDST-11377]

src/pushsource/_impl/schema/staged-schema.yaml
There are new volume types available at AWS: https://aws.amazon.com/ebs/volume-types/ , these should be added.
=> Add io2 and gp3 EC2 volume types

src/pushsource/_impl/helpers.py
If it's not desirable to check for file's existence (when timeout is 0),
the warning log notifying that the file doesn't exist shouldn't be
printed.
This fix unbreaks some pub integration tests which are now failing due
to new logs being introduced.
=> Supress warning log when not checking for file's existence

requirements.txt, src/pushsource/_impl/model/erratum_fixup.py, test-requirements.txt
In attrs version 22.1.0 the deprecated 'cmp' attribute was removed. This
has broken the dependency for pushsource, because the attributes are no
longer correctly initialized. AttrsRenamer checks whether a required
__init__ parameter is present in the created Attribute, and constructs a
new Attribute with only the present parameters. This is done with the
assumption that some constructor parameters will be removed in the
future, and this check would prevent the object construction from
breaking. In the attrs version 22.1.0 the deprecated "cmp" attribute was
removed and so it is no longer passed as an argument to the constructor.
This causes an error, since this argument is still expected in the
constructor, even though it doesn't do anything [1]. So let's also check
if the argument is in …
=> Make pushsource compatible with attrs >=22.1.0

src/pushsource/_impl/utils/containers/request.py
When there's no v2ch2 manfiest inspect fails on 404, therefore
v2ch2_list manifest was added as backup schema
=> Added v2ch2_list schema type for inspect

.github/workflows/tox-test.yml, tox.ini
To enable SAST scanning on this repository, Bandit has been added into the tox.ini and .github/workflows/tox-tests.yml files. Two tests are executed in the pipeline: bandit-exitzero and bandit.
The first scan lists all findings of low severity or higher and always passes due to the "exit-zero" option. This will allow tracking of low severity findings without stopping code from being merged in.
The second scan lists all findings of medium severity or higher and will fail the pipeline if any issues have been introduced.
=> Add bandit SAST scanning job to the CI [RHELDST-12099]

.github/workflows/tox-test.yml
Github are rolling out ubuntu-22.04 as the latest ubuntu runner. setup-python cannot install python 2.7 on that OS, so force this test environment to stick with ubuntu-20.04.
=> gh-actions: fix py27 test environment

src/pushsource/_impl/source.py, tests/source/test_source.py
Recently, a polling mechanism was introducted to pushsource to check if a file exists before continueing the push. This was necessary because mounted volumes (where the files are located) are snapmirrored and there's a time delay before new files are propagated to the snapmirror volumes. There is an unwanted side effect where all push items are checked, even those that don't contain a file in their source (namely container images that contain the image URL instead). This is undesirable behavior, because image URL is not a file and thus will never be found on disk. This bug significantly slows the pushes, since the items will be polled until timeout is reached. Fix it by only checking push item sources that start with "/", indicating that they are local files.
Refers to CLOUDDST-16707
=> Only poll for existence if item source is a file

src/pushsource/_impl/compat_attr.py
Apart from python2, the kw_only keyword argument for `attr.s()` throws `TypeError: attrs() got an unexpected keyword argument 'kw_only'` also on python3 installations using version of attrs module older than 18.2. RHEL-8 ships attrs in version 17.4, hence the argument needs to be excluded there as well.
=> Limit kw_only usage to attrs 18.2 or newer

src/pushsource/_impl/backend/staged/staged_source.py, tests/staged/test_staged_simple_rpm.py
Staged content is checked before the main polling mechanism, meaning that PushStaged code fails unless the staged content is present in the snapmirror. Add the polling mechanism to staged content. If staged path doesn't exist in the mounted volume, its existence will be polled until it appears. In this scenario it is safe to assume that the staged content is new and up-to-date.
In rare cases, existing staged content may be altered and pushed again. Since pushsource cannot know if the altered content has been propagated to snapmirror, it has to wait the full poll_timeout period to be safe. Thus, if the content already exists on the volume, wait the full period to ensure it's up to date.
This implementation assumes that push-staged is ran with only one path. Otherwise, the code will wait …
=> Poll for staged content

src/pushsource/_impl/model/azure.py, tests/model/test_vhd.py
This PR fixes a bad behaviro on `VHDPushItem.legacy_sku_id' which should only be set whenever `support_legacy` is True.
If the constraint is respected the value of `legacy_sku_id` can be any string, however the previous version was limiting it in `V1` or `V2` (same as `generation`) which shouldn't be the case.
=> Fix bad validator on VHDPushItem.legacy_sku_id

CHANGELOG.md, docs/sources/pub.rst, src/pushsource/__init__.py, src/pushsource/_impl/__init__.py, src/pushsource/_impl/backend/__init__.py, src/pushsource/_impl/backend/pub_source/__init__.py, src/pushsource/_impl/backend/pub_source/pub_client.py, src/pushsource/_impl/backend/pub_source/pub_source.py, src/pushsource/_impl/model/ami.py, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami.yml, tests/pub/data/100/images.json, tests/pub/data/123456/images.json, tests/pub/data/200/images.json, tests/pub/test_pub_amis.py, tests/pub/test_pub_client.py
Introduced new pushsource backend - `pub` for extracting push items
from Pub push item list by task id.
Pub backend currently supports extraction of AMI push items only. They
are extracted from images.json file stored on Pub service for each (AMI) task.
Little addition to AmiPushItem model class - added `image_id` attribute
that is unique identifier of AMI in AWS that is only knonw, if the AMI was
pushed previously to AWS.
=> Introduce pub source backend [RHELDST-7514]

src/pushsource/_impl/backend/staged/staged_source.py, tests/staged/test_staged_simple_rpm.py
The addition of this log caused some log-based tests in other projects to start failing due to new log messages appearing like this:
[    INFO] Directory '/tmp/aws_staged' has mtime 2023-02-05T20:28:28+00:00,
being more than 0 seconds old. Skipping the wait.
I don't think the log message makes sense anyway if the waiting feature has been disabled by setting the threshold to 0 seconds, so let's not log in that case.
=> Don't log during stagedir wait if wait is disabled

docs/sources/koji.rst, src/pushsource/_impl/backend/koji_source.py, tests/koji/test_koji_vmi.py
This PR allows `pushsource` to load Virtual Machine Images through `KojiSource`.
The VM images will come as a `VMIPushItem` or as its subclasses: `AmiPushItem` / `VHDPushItem`.
To load the VM images the application may use:
```{python}
from pushsource import Source, VMIPushItem
with Source.get('koji:https://koji.fedoraproject.org/kojihub?vmi_build=img1,img2,...') as source:
for item in source:
...  # do something
```
**NOTE:** As Koji doesn't contain all metadata for `VMIPushItem` and its subclasses it only load the common values which can be found on it. Missing information as well as specific data required for Azure or AWS may be fetched from an external service.
Refers to EXDSP-1781
=> EXDSP-1781: Allow KojiSource to retrieve VMIPushItems

src/pushsource/_impl/model/container.py, src/pushsource/_impl/model/conv.py
validation of container_list in erratum model is set to check if instance of frozen dict is frozendict.core.frozendict which is not "compatible" with frozendict.frozendict
=> Fixed frozendict convertor to core.frozendict

docs/userguide.rst
Link to PubSource class wasn't properly created in documentation
because of extra space and missing '~'.
=> Fix docs for Pub source

src/pushsource/_impl/backend/staged/staged_ami.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami.yml, tests/staged/data/simple_ami/staged.yaml, tests/staged/data/simple_ami_with_bc/staged.yaml
The `public_image` flag designates whether the AMI image is allowed to be released publicly (shared with group "all") as some images are expected to be "shipped live" by going through all the standard steps with the exception of being shared publicly.
This commit also fixes logic for getting the `ena_support` flag. Previously, when the flag was set to `False`, the
`AmiPushItem._from_data()` method unintentionally converted it to `None`. Now it remains set to `False`.
This PR relates to https://github.com/release-engineering/pubtools-ami/pull/93
=> Add public_image flag for AMI images [RHELDST-16452]

requirements.in, tox.ini
This commit fix the `tox` command on local environment by allowing the tests on `Python 3.8` to pass.
Before this commit the tests were failing on `Python 3.8` as the dependency `pytz` couldn't be installed on require-hashes mode.
This commit applies the following changes:
- Add `pytz` as a dependency for `Python < 3.9`
- Change the `pip-compile` command to run on `Python 3.8` by default
- Rebuild all requirements files using `tox`
=> Fix tox on development environment

tox.ini
The project support python3.6+
```
sh$ grep python_requires setup.py
python_requires=">=3.6",
sh$ git log -1 --oneline origin/master
b0cd3e6 (origin/master, origin/HEAD, master) Merge pull request #321 from JAVGan/fixtests
```
But it failed in tox, because pinned dependencies are for python3.9.
This is a workaround to allow testing locally with tox and older version with un-pinned dependencies
```
sh$ tox -e py37
// snip
ERROR: Could not find a version that satisfies the requirement isort==5.12.0 (from versions: 1.0.0, 1.0.1, 1.2.0, 1.2.2, 1.2.3, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.6.0, 3.6.1, 3.6.2, 3.7.0, 3.7.1, 3.7.2, 3.8.0, …
```
=> Allow to run tox localy with older version of python

.github/workflows/tox-test.yml, test-requirements.in, test-requirements.txt, tox.ini
We pin the version of Bandit SAST tool to make the CI tests more predictable. If we used the latest version available without pinning it, the CI tests could start failing on new Bandit version without any changes in our codebase.
We pin the Bandit version by adding version requirement to tox.ini.
=> Pin bandit version

src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/model/base.py, tests/baseline/cases/errata-containers-legacy-repos.yml, tests/baseline/cases/errata-containers.yml, tests/baseline/cases/koji-operator-container.yml, tests/baseline/cases/koji-source-container.yml, tests/errata/test_errata_vmis.py, tests/koji/test_koji_vmi.py
This PR changes the `KojiSource` to store the build id for containers and VMIs whenever it's available.
It adds an optional attribute `id` into the `KojiBuildInfo` model to  support the change and update the related tests.
Refers to EXDSP-2099
=> Allow KojiSource to store the build id

src/pushsource/_impl/backend/koji_source.py, tests/baseline/cases/errata-containers-legacy-repos.yml, tests/baseline/cases/errata-containers.yml, tests/baseline/cases/koji-operator-container.yml, tests/baseline/cases/koji-source-container.yml
Since container pushes were switched to Quay, this field is no longer used. However, the file's presence in the mounted volumes is still being polled before the push can begin. This can cause the pushes to take much longer than necessary. Remove the field so that the unnecessary wait is skipped.
Refers to CLOUDDST-19687
=> Remove setting src in container push items

src/pushsource/_impl/backend/staged/staged_ami.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-ami-uefi.yml, tests/baseline/cases/staged-simple-ami.yml, tests/conftest.py, tests/staged/data/simple_ami_with_bc/staged.yaml, tests/staged/data/simple_ami_with_uefi/staged.yaml
From RHEL 8.9 and RHEL 9.3 onwards UEFI will be available. The boot mode must be specified for AMI images to make use of the change. This change adds the boot mode to the metadata parsed in from composes. Data will be used by pubtools-ami and passed to cloudimg
=> Add uefi boot support to compose data [RHELDST-18235]

src/pushsource/_impl/backend/errata_source/errata_http_client.py, src/pushsource/_impl/backend/errata_source/errata_source.py, tests/baseline/test_baseline.py, tests/errata/test_errata_http_client.py
If credentials are not specified, the HTTP method returns None without querying the endpoint. This change was made because the Errata Kerberos credentials are not yet prepared and the gathered information is not yet necessary.
This unusual feature should be removed in the future.
=> Allow Errata HTTP client to work without Kerberos credentials

docs/model/ami.rst, src/pushsource/__init__.py, src/pushsource/_impl/backend/staged/staged_ami.py, src/pushsource/_impl/model/__init__.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami-bootmode.yml, tests/baseline/cases/staged-simple-ami-uefi.yml, tests/baseline/cases/staged-simple-ami.yml, tests/pub/data/123456/images.json, tests/pub/data/200/images.json, tests/pub/test_pub_amis.py
Adds to AMI ability to add access endpoint url. Used for version creation for some products in AWS Marketplace.
Refers to SPSTRAT-126
=> Adds to AMI Access Endpoint URL used for aws marketplace

src/pushsource/_impl/model/ami.py, src/pushsource/_impl/model/vms.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami-bootmode.yml, tests/baseline/cases/staged-simple-ami-uefi.yml, tests/baseline/cases/staged-simple-ami.yml, tests/model/test_vmi.py, tests/staged/data/simple_ami/staged.yaml
This commit introduces a new optional parameter on `VMIRelease` and `AmiRelease` models called `marketplace_title` which is going to be used by the pubtool as the marketplace "version title" whenever it's set, by overriding the usual version title which the pubtool was going to compute.
This is required for some layered products which requires a specialized templating title instead of the one generated by the pubtool.
With this, it will be possible to transport the template via the VMIPushItem from the source to the pubtooling which will format it into the apropriate value for the marketaplace.
Refers to SPSTRAT-116
=> Add attribute "marketplace_title" to VMIRelease

src/pushsource/_impl/compat_attr.py
importlib.metadata is available for py3.8 and later versions. This fails for py<3.8, however, it could be imported from importlib_metadata for previous versions. This patch makes it compatible for py<3.8 as the lib is used on RHEL/UBI8 with py3.6.
=> Fix importing version from importlib.metadata for py<3.8

src/pushsource/_impl/backend/koji_source.py, src/pushsource/_impl/model/vms.py, src/pushsource/_impl/schema/staged-schema.yaml, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami-bootmode.yml, tests/baseline/cases/staged-simple-ami-uefi.yml, tests/baseline/cases/staged-simple-ami.yml, tests/koji/test_koji_vmi.py
This merge provides support for generating push items from ART/rhcos builds.
=> adding support for art build

.github/workflows/tox-test.yml
In this project, "tox -e cov" already runs pytest with `--cov-fail-under=100`, thus the coverage is always enforced to remain at 100%.
Sending the coverage data to a remote service seems of little value when the coverage is already enforced at 100% when the tests are run; in fact, we probably wouldn't even reach this step if the coverage was less than 100%, since tox should have failed.
It's a common source of CI flakiness, so just drop it.
=> ci: drop codecov upload in this project

src/pushsource/_impl/backend/koji_source.py, tests/koji/fake_koji.py, tests/koji/test_koji.py
non-logged-in brew requests are not retried by default. Enable the retry to reduce push failures caused by brew connection issues.
=> Retry brew requests [CLOUDDST-22680]

README.md
- travis has not been used for testing for a long time. Replace with a github actions equivalent.
- coveralls has not been used for coverage reports for a long time. Drop it; there is no replacement as the testing workflow always enforces 100% coverage anyway.
- add a pypi badge to flesh things out a bit and show the latest release at a glance.
=> README: fix outdated badges

src/pushsource/_impl/backend/staged/staged_source.py
scandir in `_push_items_for_topdir` was reporting path strings as invalid arguments, presumably because they weren't yet available on the OCP environment. This commit places a `wait_exist` call on the path before doing anything with it. At the very least, we will now be warned if a path is inaccessible prior to failure.
=> Await dir availability while iterating StagedSource [RHELDST-25394]

src/pushsource/_impl/backend/pub_source/pub_client.py, src/pushsource/_impl/model/ami.py, tests/pub/data/123456/clouds.json, tests/pub/data/200/clouds.json, tests/pub/test_pub_amis.py, tests/pub/test_pub_client.py
Adds support for clouds.json to Pub source. 
The new implementation will try pulling images.json from a Pub task. But if not found then it will try to pull clouds.json from a Pub task.
=> Adds support for clouds.json to Pub Source [SPSTRAT-333]

src/pushsource/_impl/model/ami.py, tests/pub/test_pub_amis.py
Some fields were found to be missing that were needed for the delete function downstream. 
This is in reference to SPSTRAT-334. Testing revealed some minor issues. The MR for pubtools-marketplacesvm that provides this functionality is here: https://github.com/release-engineering/pubtools-marketplacesvm/pull/27
=> Fixes parsing of clouds.json file. 

src/pushsource/_impl/list_cmd.py, src/pushsource/_impl/model/vms.py, test-requirements.in, test-requirements.txt, tests/cmd/test_list_cmd.py
There were a few serialization issues with `pushsource-ls` command on certain field types:
- BootMode (enum)
- frozendict 
`pushsource-ls` wants to serialize push items as either YAML or as valid Python code and this was broken in some cases for these types. These are not new issues, but have been unnoticed for a while since this command is mainly for debugging and is not widely used.
This PR fixes the issues with those data types and also improves the test coverage of this command so that similar issues will be caught earlier.
=> Fix pushsource-ls handling of certain types

src/pushsource/_impl/backend/staged/staged_cloud.py, tests/baseline/cases/staged-simple-cloud.yml, tests/staged/data/simple_cloud/starmap/CLOUD_IMAGES/build1/resources.yaml, tests/staged/data/simple_cloud/starmap/CLOUD_IMAGES/build2/resources.yaml
When adding cloud to staged files version was missed as a requirement for releases. This adds that in to avoid issues with Stratosphere releases.
=> Fixes release to include version from build.

docs/model/vmi.rst, src/pushsource/__init__.py, src/pushsource/_impl/model/__init__.py, src/pushsource/_impl/model/ami.py, src/pushsource/_impl/model/vms.py, tests/baseline/cases/staged-simple-ami-bc.yml, tests/baseline/cases/staged-simple-ami-bootmode.yml, tests/baseline/cases/staged-simple-ami-uefi.yml, tests/baseline/cases/staged-simple-ami.yml, tests/baseline/cases/staged-simple-cloud.yml, tests/pub/data/100/images.json, tests/pub/data/123456/clouds.json, tests/pub/data/123456/images.json, tests/pub/data/200/clouds.json, tests/pub/data/200/images.json, tests/pub/test_pub_amis.py
This commit introduces a new optional property for all VMIPushItems named `VMICloudInformation` which stores the cloud's provider name and account alias into it.
The goal of this change is to be able to parse the patched `clouds.json` with this new property, which was introduced in
https://github.com/release-engineering/pubtools-marketplacesvm/pull/71 , allowing the DeleteTask to have a more reliable way to retrieve the provider/account information.
Refers to SPSTRAT-363
=> Add optional property "cloud_info" for VMIs

src/pushsource/_impl/model/vms.py, tests/model/test_vmi.py
This commit changes the `VMIPushItem` class to use a converter in the attribute `boot_mode` which is capable of properly converting it to the `BootMode` enum whenever possible.
It fixes issues downstream where the information is given as a string instead of the Enum.
Refers to SPSTRAT-600
=> VMIPushItem: Use converter for boot_mode
